version: '3.7'
services:
  postgres:
    container_name: '${COMPOSE_PROJECT_NAME}_postgres_prod'
    image: 'postgres:15.0-alpine'
    volumes:
      - 'guess_artistPostgresVolumeProd:/var/lib/postgresql/data'
    env_file:
      - ./server/.env.prod
    restart: always
  server:
    container_name: '${COMPOSE_PROJECT_NAME}_server_prod'
    image: '${COMPOSE_PROJECT_NAME}_server_prod:${TAG_SERVER}'
    build:
      context: .
      dockerfile: server/Dockerfile
      target: production
    env_file:
      - .env.prod
      - ./server/.env.prod
    command: 'node /usr/src/app/server/dist/main'
    depends_on:
      - postgres
    restart: always
  client:
    container_name: '${COMPOSE_PROJECT_NAME}_client_prod'
    image: '${COMPOSE_PROJECT_NAME}_client_prod:${TAG_CLIENT}'
    build:
      context: .
      dockerfile: client/Dockerfile
      target: production
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    env_file:
      - .env.prod
    restart: always
volumes:
  guess_artistPostgresVolumeProd: null
